WSOCKVDD is copyright (C) 1999 by B‚rczi G bor.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

Additional conditions:

If you make any modifications on WSOCKVDD, you have to leave the original
copyright notice intact and add a comment about your modifications.

If you distribute the binaries for WSOCKVDD from modified sources, then
you have to add a notification to the program printed at startup to tell the
user that you have made modifications and that it is not the binary from the
original sources distributed by me.

If you want to include WSOCKVDD (binaries and/or sources) in a commercial
product (on a CD-ROM for a book or something else) contact me first.

For contacting the author send electronic mail to

sting@freemail.c3.hu

